#include <stdio.h>

#include "model/node.h"
#include "parser/parser_printer.h"

/*#define JHV_DEBUG
*/
#ifdef JHV_DEBUG
#define D(DBG_OUTPUT) fprintf(output_file, "[DEBUG] %s\n", DBG_OUTPUT)
#else
#define D(DBG_OUTPUT)
#endif

extern FILE* output_file;
extern const char* output_filename;

void pp_print_root_node_(struct node *root_node)
{
  D("pp_print_root_node_");
  fprintf(output_file, "/* %s\n", output_filename);
  fprintf(output_file, "   generated by parser v.PS2\n\n");
  fprintf(output_file, "   Justin Voshell - justin.voshell@me.com\n");
  fprintf(output_file, "   CSCI E-295 Spring 2012\n");
  fprintf(output_file, "*/\n\n");
  pp_print(root_node->data.child);
}

void pp_print_translation_unit_(struct node *translation_unit)
{
	struct node *next_translation_unit = translation_unit->data.children[0];
	if (next_translation_unit) pp_print(next_translation_unit);
	pp_print(translation_unit->data.children[1]);
}
	      
void pp_print_top_level_declaration_(struct node *declaration)
{
	pp_print(declaration->data.child);
}
	 
void pp_print_declaration_(struct node *declaration)
{
  pp_print(declaration->data.children[0]);
  fputs(" ", output_file);
  pp_print(declaration->data.children[1]);
  fputs(";\n", output_file);
}
	           
void pp_print_void_type_specifier_(void)
{
	fputs("void", output_file);
}
       
void pp_print_signed_type_specifier_(struct node* signed_type_specifier)
{
	switch(signed_type_specifier->data.int_value)
	{
		case INTEGER_DATA_SIGNED_CHAR  : { fputs("signed char",      output_file); break; }
		case INTEGER_DATA_SIGNED_SHORT : { fputs("signed short int", output_file); break; }
		case INTEGER_DATA_SIGNED_INT   : { fputs("signed int",       output_file); break; }
		case INTEGER_DATA_SIGNED_LONG  : { fputs("signed long int",  output_file); break; }
		default: break;
	}
}
                                                                                       
void pp_print_unsigned_type_specifier_(struct node* unsigned_type_specifier)
{                     
	switch(unsigned_type_specifier->data.int_value)                                                                                                
	{                                                                                                                              
		case INTEGER_DATA_UNSIGNED_CHAR  : { fputs("unsigned char",      output_file); break; }                                            
		case INTEGER_DATA_UNSIGNED_SHORT : { fputs("unsigned short int", output_file); break; }                                            
		case INTEGER_DATA_UNSIGNED_INT   : { fputs("unsigned int",       output_file); break; }                                            
		case INTEGER_DATA_UNSIGNED_LONG  : { fputs("unsigned long int",  output_file); break; }                                            
		default: break;
	}
}
   	        	   
void pp_print_declarator_list_(struct node *ideclarator_list)
{
	if (ideclarator_list->data.children[0])
  {
    pp_print(ideclarator_list->data.children[0]);
    fputs(", ", output_file);
  }
  fputs("(", output_file);
  pp_print(ideclarator_list->data.children[1]);    
  fputs(")", output_file);
}

void pp_print_pointer_to_(struct node *pointer, struct node *node)
{
	if (pointer->data.child)
  {
    fputs("(*", output_file);
		pp_print_pointer_to_(pointer->data.child, node);
    fputs(")", output_file);
	}
	else if (node)
  {
    fputs("(*", output_file);
    pp_print(node);
    fputs(")", output_file);
  }
	else
	{
		fputs("(*)", output_file);
	}
}	    
	            
void pp_print_pointer_declarator_(struct node *pointer_declarator)
{
	pp_print_pointer_to_(pointer_declarator->data.children[0], pointer_declarator->data.children[1]);
}
    
void pp_print_simple_declarator_(struct node *simple_declarator)
{
  pp_print(simple_declarator->data.child);
}
          
void pp_print_identifier_(struct node *identifier)
{
	fputs(identifier->data.cstring_value, output_file);
} 

void pp_print_literal_integer_(struct node *literal_integer)
{
  fprintf(output_file, "%lu", literal_integer->data.integer_data->value);
}

void pp_print_constant_expression_(struct node *constant_expression)
{
  pp_print(constant_expression->data.child);
}

void pp_print_array_declarator_(struct node* array_declarator)
{
  fputs("(", output_file);
  pp_print(array_declarator->data.children[0]);
  fputs("[", output_file);
  if (array_declarator->data.children[1]) pp_print(array_declarator->data.children[1]);
  fputs("])", output_file);
}

void pp_print_function_declarator_(struct node* function_declarator)
{ 
  fputs("(", output_file);
  pp_print(function_declarator->data.children[0]);
  fputs("(", output_file);
  pp_print(function_declarator->data.children[1]);
  fputs("))", output_file);
}

void pp_print_parameter_type_list_(struct node* parameter_type_list)
{
  pp_print(parameter_type_list->data.child);
}

void pp_print_parameter_list_(struct node* parameter_list)
{
  if (parameter_list->data.children[0])
  {
    pp_print(parameter_list->data.children[0]);
    fputs(", ", output_file);
  }
  pp_print(parameter_list->data.children[1]);
}

void pp_print_parameter_declaration_(struct node* parameter_declaration)
{
  pp_print(parameter_declaration->data.children[0]);
  if (parameter_declaration->data.children[1])
  {
    fputs("(", output_file);
    pp_print(parameter_declaration->data.children[1]);
    fputs(")", output_file);
  }
}

void pp_print_abstract_declarator_(struct node* abstract_declarator)
{
  if (abstract_declarator->data.children[0]) pp_print_pointer_to_(abstract_declarator->data.children[0], abstract_declarator->data.children[1]);
  else if (abstract_declarator->data.children[1]) pp_print(abstract_declarator->data.children[1]);
  
}

void pp_print_direct_abstract_declarator_(struct node* direct_abstract_declarator)
{         
  fputs("(", output_file);
  if (direct_abstract_declarator->data.children[0]) pp_print(direct_abstract_declarator->data.children[0]);
  fputs("[", output_file);
  if (direct_abstract_declarator->data.children[1]) pp_print(direct_abstract_declarator->data.children[1]);
  fputs("])", output_file);
}

int pp_print(struct node *node)                                                                     
{ 
  if (!node)
  {
    fprintf(stderr, "[ERROR]: Attempt to print null parse node. Terminating output.\n");
    fputs("/*ERROR: NULL encountered.  Output terminated.*/", output_file);
    return 1;
  }
  
	switch(node->node_type)                                                                            
	{                   
    case NODE_ROOT                       : { pp_print_root_node_(node);                  break; }                                                                               
		case NODE_TRANSLATION_UNIT           : { pp_print_translation_unit_(node);           break; }                                                                                             
		case NODE_TOP_LEVEL_DECLARATION      : { pp_print_top_level_declaration_(node);      break; }                                                                                                  
		case NODE_DECLARATION                : { pp_print_declaration_(node);                break; }                                                                                                            
		case NODE_SIGNED_TYPE_SPECIFIER      : { pp_print_signed_type_specifier_(node);      break; }
		case NODE_UNSIGNED_TYPE_SPECIFIER    : { pp_print_unsigned_type_specifier_(node);    break; }                                                                                             
		case NODE_VOID_TYPE_SPECIFIER        : { pp_print_void_type_specifier_();            break; }                                                                                                    
		case NODE_DECLARATOR_LIST            : { pp_print_declarator_list_(node);            break; }                                                                                                             
		case NODE_POINTER_DECLARATOR         : { pp_print_pointer_declarator_(node);         break; }
		case NODE_SIMPLE_DECLARATOR          : { pp_print_simple_declarator_(node);          break; } 
		case NODE_IDENTIFIER                 : { pp_print_identifier_(node);                 break; }
    case NODE_LITERAL_INTEGER            : { pp_print_literal_integer_(node);            break; }
    case NODE_ARRAY_DECLARATOR           : { pp_print_array_declarator_(node);           break; }
    case NODE_CONSTANT_EXPRESSION        : { pp_print_constant_expression_(node);        break; } 
    case NODE_FUNCTION_DECLARATOR        : { pp_print_function_declarator_(node);        break; }
    case NODE_PARAMETER_TYPE_LIST        : { pp_print_parameter_type_list_(node);        break; }
    case NODE_PARAMETER_LIST             : { pp_print_parameter_list_(node);             break; }
    case NODE_PARAMETER_DECLARATION      : { pp_print_parameter_declaration_(node);      break; } 
    case NODE_ABSTRACT_DECLARATOR        : { pp_print_abstract_declarator_(node);        break; }
    case NODE_DIRECT_ABSTRACT_DECLARATOR : { pp_print_direct_abstract_declarator_(node); break; }
		default:
      fprintf(stderr, "[ERROR]: Attempt to print unknown node, type:%i", node->node_type);
      fputs("/*ERROR: Unknown node encountered.  Output terminated.*/", output_file);
      return 1;
  }
  return 0;
}