#ifndef TOKENS_H_JHV9902116
#define TOKENS_H_JHV9902116

#define IDENTIFIER           	301 
#define LITERAL_STRING       	302
#define LITERAL_NUMBER       	303
#define BREAK                	304
#define CHAR                 	305
#define CONTINUE            	306 
#define DO                  	307 
#define ELSE                	308 
#define FOR                 	309 
#define GOTO                	310 
#define IF                    311
#define INT                 	312 
#define LONG                 	313
#define RETURN              	314 
#define SHORT               	315 
#define SIGNED               	316
#define UNSIGNED            	317 
#define VOID                	318 
#define WHILE                 319
#define ASTERISK              320
#define COLON                 321
#define DASH                  322
#define PLUS                  323
#define QUESTION_MARK         324
#define ASSIGN                325
#define ASSIGN_BITWISE_AND    326
#define ASSIGN_BITWISE_OR     327
#define ASSIGN_BITWISE_XOR    328
#define ASSIGN_LEFT_SHIFT     329
#define ASSIGN_RIGHT_SHIFT    330
#define ASSIGN_SUM            331
#define ASSIGN_DIFFERENCE     332
#define ASSIGN_PRODUCT        333
#define ASSIGN_QUOTIENT       334
#define ASSIGN_REMAINDER      335
#define BITWISE_AND           336
#define BITWISE_OR            337
#define BITWISE_XOR           338
#define BITWISE_NEGATION      339
#define LEFT_SHIFT            340
#define RIGHT_SHIFT           341
#define DIVISION              342
#define REMAINDER             343
#define INCREMENT             344
#define DECREMENT             345
#define LESS                  346
#define LESS_OR_EQUAL         347
#define GREATER               348
#define GREATER_OR_EQUAL      349
#define EQUAL_TO              350
#define NOT_EQUAL             351
#define LOGICAL_AND           352
#define LOGICAL_OR            353
#define LOGICAL_NEGATION      354
#define LEFT_PAREN            355
#define RIGHT_PAREN           356 
#define LEFT_BRACKET          357
#define RIGHT_BRACKET         358
#define LEFT_BRACE            359
#define RIGHT_BRACE           360
#define STATEMENT_TERMINATOR  361
#define SEQUENTIAL_EVAL       362

int token_has_attribute(int token);

#endif /*TOKENS_H_JHV9902116*/